### ISSUE TITLE
Issues on Windows 10 [SOLVED]

### ISSUE THREAD

**Issue by marconij** [byuflowlab/Mex.jl#2]
Hello,

I had some problems with the installation and the working of this package, and since _I've already solved them_ I tought to share my findings in case someone incurred in the same issues.

I'm currently using _Windows 10_, _Matlab R2019a_ and _Julia 1.2.0-2_. 
MEX on matlab is configured to use 'MinGW64 Compiler (C++)' for C++ language compilation. 

**Problem 1** (installation): using "]add https://github.com/byuflowlab/Mex.jl" in Julia used to work for everything except for the compilation of mexjulia. However, this doesn't throw an error. Looking in "...\\.juliapro\JuliaPro_v1.2.0-2\packages\Mex\ZlRZN\deps" and reading the textfile "build" at the very end it says 

> "Error using mex
> g++: error: ...\AppData\Local\JuliaPro-1.1.1.1\Julia-1.1.1\bin\libjulia.dll.a: No such file or directory"

... and indeed the file "libjulia.dll.a" does not exist, whereas "libjulia.dll" does. To fix it, I naively copied "libjulia.dll" in the same folder and renamed it as "libjulia.dll.a". To my surprise, it worked and the compilation was successful.

**Problem 2** (find libraries): I then tried to run jl.eval('1+1') in MATLAB, but it returned an error saying that some libraries could not be found. Long story short, I think there was a problem with the paths, and my fix was to change the jl.m (class definition) at lines 136-146 switching the order of the two operations, that is:
ORIGINAL:
```
                % tweak path to find shared libs
                if ispc
                    % This is a hack for windows which lets the mex function
                    % find the julia dlls during initialization without requiring that
                    % julia be on the path.
                    old_dir = pwd;
                    cd(jl.julia_home);
                end

                % basic runtime initialization
                jldict = load('jldict', 'julia_home', 'sys_image', 'lib_path');
```

MODIFIED:
```
                % basic runtime initialization
                jldict = load('jldict', 'julia_home', 'sys_image', 'lib_path');
                
                % tweak path to find shared libs
                if ispc
                    % This is a hack for windows which lets the mex function
                    % find the julia dlls during initialization without requiring that
                    % julia be on the path.
                    old_dir = pwd;
                    cd(jldict.julia_home);
                end
```

Possibly I'm the only one experiencing these issues, but I wanted to share : )

**Comment by hqs811** [comment]
Hi, you are not the only one who had experienced this, thank you so much for sharing it!

However, after fixing these two problems the Matlab crashes when it run jl.eval('2+2'). Any idea how to fix it?

**Comment by taylormcd** [comment]
This should be resolved in the most current version of this package.
