### ISSUE TITLE
Matlab closes quickly after executing  mexjulia

### ISSUE THREAD

**Issue by WouterJRV** [byuflowlab/Mex.jl#5]
Hi! I just tried this out and encountered the following issues (on Ubuntu 20.04)
 *) I had to add the package to the MATLAB path manually
*) jlexec statements execute and return, but a few seconds later matlab just closes without without warning

**Comment by maartenvd** [comment]
can you try this branch? https://github.com/jebej/Mex.jl I had the same problem, and I think it's solved after turning off signals.

**Comment by WouterJRV** [comment]
> can you try this branch? https://github.com/jebej/Mex.jl I had the same problem, and I think it's solved after turning off signals.

Thanks, this one seems to work!

**Comment by WouterJRV** [comment]
> can you try this branch? https://github.com/jebej/Mex.jl I had the same problem, and I think it's solved after turning off signals.

Hi, it's not perfect yet. ML doesn't close instantly, but it can still close at later times pretty randomly. For example when I work a bit on another program and then click the matlab window again

**Comment by taylormcd** [comment]
The downstream changes have now been incorporated into this repository along with a bunch of other changes.  So at least the immediate crashing problem is fixed.
